---
title: "dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
data("instacart")
set.seed(123)

most_aisle_orders = instacart %>%
  count(aisle, sort = T)
  
most_aisle_orders %>% 
  filter(n > 10000) %>% 
  mutate(aisle = fct_reorder(aisle, -n)) %>% 
  plot_ly(x = ~aisle, y = ~n, type = "bar", color = ~aisle)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
common_product = instacart %>% 
  count(product_name, sort = T) %>% 
  sample_n(20)

inner_join(instacart, common_product, by = "product_name") %>% 
  mutate(product_name = fct_reorder(product_name, days_since_prior_order)) %>%   plot_ly(x = ~product_name, y = ~days_since_prior_order, type = "box")
```

### Chart C

```{r}
instacart %>% 
  filter(aisle == "packaged vegetables fruits") %>% 
  group_by(product_name) %>% 
  mutate(mean_ord_hr = mean(order_hour_of_day)) %>% 
  select(product_name, mean_ord_hr) %>% 
  distinct() %>% 
  plot_ly(x = ~product_name, y = ~mean_ord_hr, type = "scatter" ,mode = "markers")
```


